# Docker compose config for mongo and mongo-express testing and debugging
version: '3.1'
services:
  mongo:
    container_name: ahandfortheband-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ahandfortheband-mongo-data:/data/db
      - ahandfortheband-mongo-config:/data/configdb
  mongo-express:
    container_name: ahandfortheband-mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  ahandfortheband-mongo-data:
  ahandfortheband-mongo-config:
