logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
    '[org.springframework.security]': INFO

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/admin
      auto-index-creation: true
      database: ahandfortheband
